# What is function Transformer in machine learning?

# The function transformer is a tool in scikit learn , a popularbPython library for machine learning , that allows you to apply a specified function to the input data.The function Transformer can useful for performing custom transformations of input data in ML pipeline

# The function Transformer takes as input a single function that will be applied to each sample in the data . This function can be any Python function that takes a single argument , such as a lambda function or a user-defined fucntion. The function should return the transformed sample

In [5]:


from sklearn. preprocessing import FunctionTransformer 
import numpy as np 

#create a dataset
x=np.array([[1,2],[3,4]])

#define the transformation function
log_transform = FunctionTransformer(np.log1p)

#apply the transformer to the dataset
x_transformed = log_transform.transform(x)

#view the transformed data
print(x_transformed)

[[0.69314718 1.09861229]
 [1.38629436 1.60943791]]


# PRACTICAL USECASES

# 1. Custom Feature Enginerring

In [11]:
from sklearn.preprocessing import FunctionTransformer
import numpy as np 

#create a dataset
X = np.array([[1,2],[3,4]])

#deine a functionTransformer to apply the custom function

def my_feature_engineering(X):
    return np.hstack((X,X**2))

#create a Function Transformer to apply the custom function

custom_transformer = FunctionTransformer(my_feature_engineering)
 
    
#apply the transformer to the input data
X_transformed = custom_transformer.transform(X)

#view the transformed data

print(X_transformed)


[[ 1  2  1  4]
 [ 3  4  9 16]]


# 2. Scaling and Normalization



In [4]:
from sklearn.preprocessing import FunctionTransformer
import numpy as np

X = np.array([[1,2],[3,4]])

def my_scaling(X):
    return X / np.max(X)

custom_transformer = FunctionTransformer(my_scaling)

X_transformed = custom_transformer.transform(X)

print(X_transformed)

[[0.25 0.5 ]
 [0.75 1.  ]]


# 3. Data Cleaning

In [10]:
from sklearn.preprocessing import FunctionTransformer
import numpy as np

X= np.array([[1,2],[3,np.nan]])

def my_cleaning(X):
    X[np.isnan(X)]=0
    return X
custom_transformer =FunctionTransformer(my_cleaning)

X_transformed = custom_transformer.transform(X)

print(X_transformed)


[[1. 2.]
 [3. 0.]]


# FUNCTION TRANSFORMER APPLY ON DATASET

In [13]:
import numpy as np
import pandas as pd


In [14]:
df=pd.read_csv("C:\\Users\\jyoti\\OneDrive\\Desktop\\New folder\\covid_toy.csv")


In [15]:
df.head(2)

age gender  fever cough     city has_covid
0   60   Male  103.0  Mild  Kolkata        No
1   27   Male  100.0  Mild    Delhi       Yes

In [16]:
from sklearn.preprocessing import LabelEncoder

In [17]:
lb = LabelEncoder()

In [36]:
df['gender']=lb.fit_transform(df['gender'])
df['cough']=lb.fit_transform(df['cough'])
df['city']=lb.fit_transform(df['city'])
df['has_covid']=lb.fit_transform(df['has_covid'])

KeyError: 'gender'

# applying on Tips dataset

In [24]:
df=pd.read_csv("C:\\Users\\jyoti\\OneDrive\\Desktop\\New folder\\tips.csv")

In [25]:
df.head(2)

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3

In [26]:
lb =  LabelEncoder()


In [27]:
df['sex']=lb.fit_transform(df['sex'])
df['smoker']=lb.fit_transform(df['smoker'])
df['day']=lb.fit_transform(df['day'])
df['time']=lb.fit_transform(df['time'])

In [28]:
df.head()

total_bill   tip  sex  smoker  day  time  size
0       16.99  1.01    0       0    2     0     2
1       10.34  1.66    1       0    2     0     3
2       21.01  3.50    1       0    2     0     3
3       23.68  3.31    1       0    2     0     2
4       24.59  3.61    0       0    2     0     4

In [30]:
from sklearn.preprocessing import FunctionTransformer

In [31]:
tf= FunctionTransformer(np.log1p)

In [34]:
new_df = tf.fit_transform(df)

In [35]:
new_df

total_bill       tip       sex    smoker       day  time      size
0      2.889816  0.698135  0.000000  0.000000  1.098612   0.0  1.098612
1      2.428336  0.978326  0.693147  0.000000  1.098612   0.0  1.386294
2      3.091497  1.504077  0.693147  0.000000  1.098612   0.0  1.386294
3      3.205993  1.460938  0.693147  0.000000  1.098612   0.0  1.098612
4      3.242202  1.528228  0.000000  0.000000  1.098612   0.0  1.609438
..          ...       ...       ...       ...       ...   ...       ...
239    3.402197  1.934416  0.693147  0.000000  0.693147   0.0  1.386294
240    3.338613  1.098612  0.000000  0.693147  0.693147   0.0  1.098612
241    3.164208  1.098612  0.693147  0.693147  0.693147   0.0  1.098612
242    2.934920  1.011601  0.693147  0.000000  0.693147   0.0  1.098612
243    2.984671  1.386294  0.000000  0.000000  1.386294   0.0  1.098612

[244 rows x 7 columns]