In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.read_csv("C:\\Users\\jyoti\\OneDrive\\Desktop\\New folder\\covid_toy.csv")

In [3]:
df.head()

age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [4]:
df=df.drop(columns=['age','fever'],axis=1)

In [5]:
df.head()

gender cough     city has_covid
0    Male  Mild  Kolkata        No
1    Male  Mild    Delhi       Yes
2    Male  Mild    Delhi        No
3  Female  Mild  Kolkata        No
4  Female  Mild   Mumbai        No

In [6]:
from sklearn.preprocessing import OrdinalEncoder

In [7]:
df['gender'].value_counts()

gender
Female    59
Male      41
Name: count, dtype: int64

In [9]:
df['cough'].value_counts()

cough
Mild      62
Strong    38
Name: count, dtype: int64

In [10]:
df['city'].value_counts()

city
Kolkata      32
Bangalore    30
Delhi        22
Mumbai       16
Name: count, dtype: int64

In [11]:
df['has_covid'].value_counts()

has_covid
No     55
Yes    45
Name: count, dtype: int64

In [13]:
oe=OrdinalEncoder(categories=[['Male','Female'],['Mild','Strong'],
                             ['Kolkata','Bangalore','Delhi','Mumbai'],['No','Yes']])

In [14]:
oe

OrdinalEncoder(categories=[['Male', 'Female'], ['Mild', 'Strong'],
                           ['Kolkata', 'Bangalore', 'Delhi', 'Mumbai'],
                           ['No', 'Yes']])

In [15]:
oe.fit(df)

OrdinalEncoder(categories=[['Male', 'Female'], ['Mild', 'Strong'],
                           ['Kolkata', 'Bangalore', 'Delhi', 'Mumbai'],
                           ['No', 'Yes']])

In [16]:
new_df=oe.transform(df)

In [17]:
new_df

array([[0., 0., 0., 0.],
       [0., 0., 2., 1.],
       [0., 0., 2., 0.],
       [1., 0., 0., 0.],
       [1., 0., 3., 0.],
       [1., 0., 1., 1.],
       [0., 1., 1., 0.],
       [1., 1., 3., 1.],
       [1., 1., 1., 0.],
       [1., 0., 2., 0.],
       [1., 0., 2., 0.],
       [1., 0., 3., 1.],
       [1., 1., 0., 0.],
       [0., 0., 1., 1.],
       [0., 0., 1., 0.],
       [0., 1., 0., 1.],
       [1., 0., 0., 1.],
       [1., 1., 2., 0.],
       [1., 0., 1., 1.],
       [1., 1., 1., 1.],
       [0., 1., 1., 0.],
       [0., 0., 1., 1.],
       [1., 1., 0., 1.],
       [1., 0., 2., 1.],
       [1., 1., 0., 0.],
       [0., 0., 3., 0.],
       [1., 0., 0., 1.],
       [1., 1., 2., 0.],
       [0., 0., 0., 0.],
       [1., 1., 3., 1.],
       [0., 0., 2., 1.],
       [0., 0., 0., 0.],
       [1., 1., 2., 1.],
       [1., 0., 0., 0.],
       [0., 0., 3., 1.],
       [1., 1., 1., 0.],
       [1., 0., 1., 0.],
       [0., 0., 0., 0.],
       [1., 0., 2., 1.],
       [1., 0., 0., 0.],


In [18]:
df=pd.read_csv("C:\\Users\\jyoti\\OneDrive\\Desktop\\New folder\\tips.csv")

In [19]:
df.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [20]:
df=df.drop(columns=['total_bill','tip','size'],axis=1)

In [21]:
df.head()

sex smoker  day    time
0  Female     No  Sun  Dinner
1    Male     No  Sun  Dinner
2    Male     No  Sun  Dinner
3    Male     No  Sun  Dinner
4  Female     No  Sun  Dinner

In [22]:
from sklearn.preprocessing import OrdinalEncoder

In [23]:
df['sex'].value_counts()

sex
Male      157
Female     87
Name: count, dtype: int64

In [24]:
df['smoker'].value_counts()

smoker
No     151
Yes     93
Name: count, dtype: int64

In [25]:
df['day'].value_counts()

day
Sat     87
Sun     76
Thur    62
Fri     19
Name: count, dtype: int64

In [26]:
df['time'].value_counts()

time
Dinner    176
Lunch      68
Name: count, dtype: int64

In [31]:

oe=OrdinalEncoder(categories=[['Male','Female'],['No','Yes'],
                             ['Sat','Sun','Thur','Fri'],['Dinner','Lunch']])

In [32]:
oe

OrdinalEncoder(categories=[['Male', 'Female'], ['No', 'Yes'],
                           ['Sat', 'Sun', 'Thur', 'Fri'], ['Dinner', 'Lunch']])

In [33]:
oe.fit(df)

OrdinalEncoder(categories=[['Male', 'Female'], ['No', 'Yes'],
                           ['Sat', 'Sun', 'Thur', 'Fri'], ['Dinner', 'Lunch']])

In [34]:
new_df=oe.transform(df)

In [36]:
new_df=pd.DataFrame(new_df,columns=df.columns)

In [37]:
new_df

sex  smoker  day  time
0    1.0     0.0  1.0   0.0
1    0.0     0.0  1.0   0.0
2    0.0     0.0  1.0   0.0
3    0.0     0.0  1.0   0.0
4    1.0     0.0  1.0   0.0
..   ...     ...  ...   ...
239  0.0     0.0  0.0   0.0
240  1.0     1.0  0.0   0.0
241  0.0     1.0  0.0   0.0
242  0.0     0.0  0.0   0.0
243  1.0     0.0  2.0   0.0

[244 rows x 4 columns]

# Method -2 get_dummies()=>> to solve overfitting

In [39]:
df=pd.read_csv("C:\\Users\\jyoti\\OneDrive\\Desktop\\New folder\\covid_toy.csv")

In [40]:
df.head()

age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [41]:
pd.get_dummies(df, columns=['gender','cough','city'])

age  fever has_covid  gender_Female  gender_Male  cough_Mild  \
0    60  103.0        No          False         True        True   
1    27  100.0       Yes          False         True        True   
2    42  101.0        No          False         True        True   
3    31   98.0        No           True        False        True   
4    65  101.0        No           True        False        True   
..  ...    ...       ...            ...          ...         ...   
95   12  104.0        No           True        False        True   
96   51  101.0       Yes           True        False       False   
97   20  101.0        No           True        False        True   
98    5   98.0        No           True        False       False   
99   10   98.0       Yes           True        False       False   

    cough_Strong  city_Bangalore  city_Delhi  city_Kolkata  city_Mumbai  
0          False           False       False          True        False  
1          False           False        True         False        False  
2          False           False        True         False        False  
3          False           False       False          True        False  
4          False           False       False         False         True  
..           ...             ...         ...           ...          ...  
95         False            True       False         False        False  
96          True           False       False          True        False  
97         False            True       False         False        False  
98          True           False       False         False         True  
99          True           False       False          True        False  

[100 rows x 11 columns]

In [42]:
pd.get_dummies(df,columns=['gender','cough','city'],drop_first= True)

age  fever has_covid  gender_Male  cough_Strong  city_Delhi  city_Kolkata  \
0    60  103.0        No         True         False       False          True   
1    27  100.0       Yes         True         False        True         False   
2    42  101.0        No         True         False        True         False   
3    31   98.0        No        False         False       False          True   
4    65  101.0        No        False         False       False         False   
..  ...    ...       ...          ...           ...         ...           ...   
95   12  104.0        No        False         False       False         False   
96   51  101.0       Yes        False          True       False          True   
97   20  101.0        No        False         False       False         False   
98    5   98.0        No        False          True       False         False   
99   10   98.0       Yes        False          True       False          True   

    city_Mumbai  
0         False  
1         False  
2         False  
3         False  
4          True  
..          ...  
95        False  
96        False  
97        False  
98         True  
99        False  

[100 rows x 8 columns]

In [43]:
#sequence==> model (overfitting/Memorization)==> 1 data 100% , 2 data 40%

# Method -3 OneHot Encoding

In [44]:
from sklearn.preprocessing import OneHotEncoder

In [45]:
oe=OneHotEncoder(drop='first',sparse=False)

In [46]:
df.head(3)


age gender  fever cough     city has_covid
0   60   Male  103.0  Mild  Kolkata        No
1   27   Male  100.0  Mild    Delhi       Yes
2   42   Male  101.0  Mild    Delhi        No

In [47]:
df_new=oe.fit_transform(df[['gender','cough','city','has_covid']])

C:\Users\jyoti\anaconda3\Lib\site-packages\sklearn\preprocessing\_encoders.py:972: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


In [48]:
df_new

array([[1., 0., 0., 1., 0., 0.],
       [1., 0., 1., 0., 0., 1.],
       [1., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.],
       [1., 1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 1., 1.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 1.],
       [0., 1., 0., 1., 0., 0.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0.],
       [1., 1., 0., 1., 0., 1.],
       [0., 0., 0., 1., 0., 1.],
       [0., 1., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1.],
       [0., 1., 0., 0., 0., 1.],
       [1., 1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 1.],
       [0., 1., 0., 1., 0., 1.],
       [0., 0., 1., 0., 0., 1.],
       [0., 1., 0., 1., 0., 0.],
       [1., 0., 0., 0., 1., 0.],
       [0., 0., 0., 1., 0., 1.],
       [0., 1., 1., 0., 0., 0.],
       [1., 0., 0., 1., 0., 0.],
       [0., 1., 0., 0., 1., 1.],
       [1.

In [49]:
df=pd.read_csv("C:\\Users\\jyoti\\OneDrive\\Desktop\\New folder\\tips.csv")

In [50]:
df.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [51]:
from sklearn.preprocessing import OneHotEncoder

In [52]:
oe=OneHotEncoder(drop='first',sparse=False)

In [53]:
df.head(3)


total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3

In [54]:
df_new=oe.fit_transform(df[['sex','smoker','day','time']])

C:\Users\jyoti\anaconda3\Lib\site-packages\sklearn\preprocessing\_encoders.py:972: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


In [55]:
df_new

array([[0., 0., 0., 1., 0., 0.],
       [1., 0., 0., 1., 0., 0.],
       [1., 0., 0., 1., 0., 0.],
       ...,
       [1., 1., 1., 0., 0., 0.],
       [1., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0.]])

# Label encoding

In [56]:
from sklearn.preprocessing import LabelEncoder

In [57]:
df=pd.read_csv("C:\\Users\\jyoti\\OneDrive\\Desktop\\New folder\\covid_toy.csv")

In [58]:
df.head()

age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [59]:
lb=LabelEncoder()

In [60]:
df['gender']=lb.fit_transform(df['gender'])
df['cough']=lb.fit_transform(df['cough'])
df['city']=lb.fit_transform(df['city'])
df['has_covid']=lb.fit_transform(df['has_covid'])

In [61]:
df.head()

age  gender  fever  cough  city  has_covid
0   60       1  103.0      0     2          0
1   27       1  100.0      0     1          1
2   42       1  101.0      0     1          0
3   31       0   98.0      0     2          0
4   65       0  101.0      0     3          0